### ISSUE TITLE
Dependency issue on Arch Linux

### ISSUE THREAD

**Issue by doubledge-spec** [ClementJ18/moddb#34]
In the extras repository, there is a package for moddb. If I run pip check I get this:
```
pip check
moddb 0.8.1 has requirement beautifulsoup4==4.6.3, but you have beautifulsoup4 4.12.2.
moddb 0.8.1 has requirement pyrate-limiter==2.8.1, but you have pyrate-limiter 2.10.0.
moddb 0.8.1 has requirement toolz==0.11.2, but you have toolz 0.12.0.
```
Is it possible to update what moddb requests?

**Comment by gothicVI** [comment]
Any plans on when it's going to be released?

**Comment by ClementJ18** [comment]
I need to finish the implementation of tags and merge but my tests are giving me trouble. I will probably give it another shot soon. I have a few releases upcoming for other projects I need to wrap up first.

**Comment by ClementJ18** [comment]
v0.9.0 has now been released
