### ISSUE TITLE
Currently Unable to Package Newest Versions of Moddb due to Python Ratelimer 2.x instead of 3.x usage.

### ISSUE THREAD

**Issue by BunnyApocalypse** [ClementJ18/moddb#43]
Hi Clement,

I'm the Fedora packager of moddb as a part of maintaining Lutris.

Unfortunately, the most recent version is not really packageable because moddb now uses python2.x specific functions of pyrate_limiter.

Previously, I guess luckily the versions worked using the newer 3.x versions of pyrate_limiter we have packaged in Fedora, but this seems to no longer be the case.

Would you be able to swap out the use of the 2.x version of the library for the 3.x one?

**Comment by ClementJ18** [comment]
I think I remember trying to upgrade before, and there were some large breaking changes under the hood (and over it). I can have another look at some point

**Comment by BunnyApocalypse** [comment]
hey yeah I've been trying to do a port to 3.x as well over here since i figured it might've been a fast project.

Got a great error by accidentally ratelimiting myself while trying to run the test suite: "Check back 7 minutes ago"

![grafik](https://github.com/ClementJ18/moddb/assets/8812653/551d0c36-3077-4ad2-a86a-6aa810a9e7ca)

I gotta go to bed for now but I'll throw my changes onto a fork for you to look at if you want, although I'm sure your attempts were better than mine.

**Comment by BunnyApocalypse** [comment]
here's the commit with my current changes: https://github.com/ClementJ18/moddb/compare/develop...BunnyApocalypse:moddb:develop

**Comment by farchord** [comment]
Hello Clement,

I saw this patch on the archlinux package, would it help in this case?

https://gitlab.archlinux.org/archlinux/packaging/packages/python-moddb/-/issues/1

**Comment by farchord** [comment]
I went ahead and built this in copr (For Fedora) here: https://copr.fedorainfracloud.org/coprs/farchord/moddb-fix/builds/ it builds and imports fine. Tomorrow I'll try to run more python tests against it.

**Comment by farchord** [comment]
Btw if the patch is good, let me know I can create a PR with it

**Comment by ClementJ18** [comment]
Could you test the patch against the example detailed in this discussion thread: https://github.com/vutran1710/PyrateLimiter/discussions/150

If it doesn't generate any traceback, then I have a look at it.

**Comment by ClementJ18** [comment]
I've removed pyrate as an extension in favor of my own implementation. It works for now, I will refine the implementation in the future
