### ISSUE TITLE
0.11.0...?

### ISSUE THREAD

**Issue by farchord** [ClementJ18/moddb#46]
Good morning @ClementJ18, 

Happy Easter, if you observe this holiday!

Is version 0.11.0 ready to go? Just checking before I do a release for Fedora. I didn't see a tagged commit.

Thanks!

**Comment by ClementJ18** [comment]
Not yet, there's a few more things I want to look at before I release the version

**Comment by farchord** [comment]
> Not yet, there's a few more things I want to look at before I release the version

Cool beans, thank you!

**Comment by ClementJ18** [comment]
0.11.0 has been released
