### ISSUE TITLE
Addon.save() does not work

### ISSUE THREAD

**Issue by Xabab** [ClementJ18/moddb#6]
When trying to save addon (e.g. https://www.moddb.com/mods/stalker-anomaly/addons/anomaly-hd-models-addon),

```
class File(BaseMetaClass):
    def save(self, path = None): 
        mirror = join(download.find("a", string=f"download {self.name}")["href"])
```
throws `TypeError: 'NoneType' object is not subscriptable` because it tries to search for an addon title instead for a filename

![image](https://user-images.githubusercontent.com/14582595/133948326-00cb99d3-82c4-45ad-b25d-7b317c5c13c1.png)

Simply needs to be changed to:

`mirror = join(download.find("a", string=f"download {self.filename}")["href"])`

**Comment by ClementJ18** [comment]
Fixed in [22c92e3](https://github.com/ClementJ18/moddb/pull/15/commits/22c92e3b353c4fea57d875e86f4fcbc234b15dc2)
