### ISSUE TITLE
Huge RAM usage when trying to download a huge file

### ISSUE THREAD

**Issue by Xabab** [ClementJ18/moddb#7]
With an issue fix from https://github.com/ClementJ18/moddb/issues/6 I still have problems downloading a huge file, because current code tries to fit it in RAM whole

https://stackoverflow.com/questions/16694907/download-large-file-in-python-with-requests

This could help

**Comment by ClementJ18** [comment]
Fixed in [22c92e3](https://github.com/ClementJ18/moddb/pull/15/commits/22c92e3b353c4fea57d875e86f4fcbc234b15dc2)
